config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  authenticated :user do
    root to: "groups#index", as: :authenticated_root
  end
  
  unauthenticated :user do
    root "splash#index"
  end
  # Defines the root path route ("/")
  # root "articles#index"
  
  resources :groups, only: [:new, :create] do
    resources :products, only: [:index, :new, :create]
  end
  devise_scope :user do
    get 'signout', to: 'users/sessions#destroy'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :products
  has_one_attached :icon, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :icon, presence: true

  def total_amount
    total = 0.0
    products.each do |product|
      total += product.amount
    end
    total
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :groups
  belongs_to :author, class_name: 'User'

  validates :name, presence: true
  validates :amount, comparison: { greater_than: 0 }
  validates :groups, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: 'author_id'
  has_many :products, foreign_key: 'author_id'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @groups = current_user.groups.all
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to root_path
      flash[:alert] = 'Your category was created successfully'
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = 'Your category was not created'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @group = current_user.groups.find(params[:group_id])
    @products = @group.products.all.order(created_at: :DESC)
  end

  def new
    @groups = current_user.groups.all
    @product = current_user.products.new
  end

  def create
    @product = current_user.products.new(product_params)
    @product.groups << Group.find(params[:groups]) unless params[:groups].nil?
    if @product.save
      redirect_to root_path
      flash[:alert] = 'Your product was created successfully'
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = 'Your product was not created'
    end
  end

  private

  def product_params
    params.permit(:name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
    @button = 'signup'
    @title = 'register'
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/groups/index.html.erb
<navbar class="navbar">
  <i class="fa-solid fa-bars"></i>
  <span>CATEGORIES</span>
  <i class="fa-solid fa-magnifying-glass"></i>
</navbar>
<% @groups.each do |group| %>
  <%= link_to group_products_path(group) do %>
    <div class="card"> 
      <% if group.icon.attached? %>
        <%= image_tag group.icon, class: 'group-icon' %> 
      <% else %>
        <%= image_tag("no_image_icon.svg", class: 'group-icon') %> 
      <% end %>
      <span><%= group.name %></span>
      <span>$<%= group.total_amount %></span>
    </div>
  <% end %>
<% end %>
<%= button_to 'add a new category', new_group_path, method: :get, class: "add-new-button" %>

app/views/groups/new.html.erb
<navbar class="navbar">
  <%= link_to root_path do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  <span>NEW CATEGORY</span>
  <i class="fa-solid fa-magnifying-glass"></i>
</navbar>
<%= form_with model: @group do |f| %>
  <%= f.text_field :name, placeholder: 'Name', class: 'fields' %>
  <%= f.file_field :icon %>
  <%= f.submit 'save', class: 'add-new-button' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  </head>

  <body class="main-container">
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<navbar class="navbar">
  <%= link_to root_path do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  <span>PRODUCTS</span>
  <i class="fa-solid fa-magnifying-glass"></i>
</navbar>
<div class="products-total">
  <span>Total</span>
  <span>$<%= @group.total_amount %></span>
</div>
<% @products.each do |product| %>
  <div class="card"> 
    <span><%= product.name %></span>
    <span>$<%= product.amount %></span>
  </div>
<% end %>
<%= button_to 'add a new product', new_group_product_path, method: :get, class: "add-new-button" %>

app/views/products/new.html.erb
<navbar class="navbar">
  <%= link_to group_products_path do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  <span>NEW PRODUCT</span>
  <i class="fa-solid fa-magnifying-glass"></i>
</navbar>
<%= form_with url: group_products_path do |f| %>
  <%= f.text_field :name, placeholder: 'Name', class: 'fields' %>
  <%= f.number_field :amount, placeholder: 0, step: :any, class: 'fields' %>
  <div class="categories">
    <%= f.label :group, 'Choose all the categories you want to add (must be one at least)' %>
    <% @groups.each do |group| %>
      <div>
        <%= f.check_box :groups, { multiple: true }, group.id, false %>
        <%= f.label group.name %>
      </div>
    <% end %>
  </div>
  <%= f.submit 'save', class: 'add-new-button' %>
<% end %>

app/views/splash/index.html.erb
  <div class='splash-title'>
    <span>Shopping record</span>
  </div>
  <div class="splash-buttons">
    <%= button_to 'log in', new_user_session_path, method: :get, class: "splash-button loggin" %>
    <%= button_to 'sign up', new_user_registration_path, method: :get, class: "splash-button signup" %>
  </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>